"""Concrete provider transports + a name→generator registry.

Implementation is split (#456):

- ``provider_telemetry`` — watchdog, concurrency, ``TelemetryContext``
- ``provider_transports`` — HTTP, Vertex, subscription, failover
- ``provider_factories`` — route tables and ``make_*`` factories

This module re-exports the previous public (and test) surface so callers do
not need to change imports.
"""

from __future__ import annotations

from hramatka.engine.provider_factories import (
    ALLOWED_MODELS,
    RoundRobinGeneratorSelector,
    _build_generator_port,
    _gemini_ais_route,
    _gemini_routes,
    _gemma_routes,
    _require_exact_qualified_routes,
    _require_qualification_route,
    _with_failover,
    make_bake_generator,
    make_generator,
    make_logical_model_generator,
    make_qualification_pinned_generator,
    qualification_route_credential_present,
    validate_and_get_model,
    validate_qualification_route_runtime,
)
from hramatka.engine.provider_telemetry import (
    LATENCY_WATCHDOG_MIN_SAMPLES,
    LATENCY_WATCHDOG_MULTIPLIER,
    LATENCY_WATCHDOG_WINDOW,
    ProviderConcurrencyBudget,
    TelemetryContext,
    configure_provider_concurrency,
    evaluate_latency_watchdog,
    json_mode_enabled_for_model,
    provider_call_slot,
    telemetry_ctx,
)
from hramatka.engine.provider_transports import (
    DEEPINFRA_API_KEY_ENV,
    DEEPINFRA_BASE_URL_ENV,
    DEEPINFRA_MODEL,
    DEEPSEEK_API_KEY_ENV,
    DEEPSEEK_BASE_URL_ENV,
    DEEPSEEK_MODEL,
    DEEPSEEK_V4_FLASH_MODEL,
    DEEPSEEK_V4_PRO_MODEL,
    DEFAULT_DEEPINFRA_BASE_URL,
    DEFAULT_DEEPSEEK_BASE_URL,
    DEFAULT_GEMMA_AIS_BASE_URL,
    DEFAULT_GEMMA_FALLBACK_BASE_URL,
    DEFAULT_GEMMA_FALLBACK_MODEL,
    DEFAULT_SUBSCRIPTION_EXECUTABLE,
    DEFAULT_SUBSCRIPTION_MODEL,
    GEMMA_AIS_BASE_URL_ENV,
    GEMMA_FALLBACK_API_KEY_ENV,
    GEMMA_FALLBACK_API_KEY_FILE_ENV,
    GEMMA_FALLBACK_BASE_URL_ENV,
    GEMMA_FALLBACK_MODEL_ENV,
    SUBSCRIPTION_EXECUTABLE_ENV,
    SUBSCRIPTION_HOST,
    SUBSCRIPTION_MODEL_ENV,
    SUBSCRIPTION_PROVIDER,
    VERTEX_API_KEY_ENV,
    VERTEX_API_KEY_FILE_ENV,
    VERTEX_BASE_URL_ENV,
    FailoverGeneratorPort,
    HttpChatTransport,
    SubscriptionGeneratorPort,
    VertexGenerateContentTransport,
    _extract_text,
    _extract_vertex_text,
    _get_bake_providers,
    _validate_vertex_base_url,
)
from hramatka.engine.transport import (
    AIS_API_KEY_ENV,
    AIS_API_KEY_FILE_ENV,
    GEMMA_MODEL,
    GEMMA_TIMEOUT_S,
    AISGeneratorPort,
    GeneratorUnavailable,
    generator_model_id,
)

__all__ = [
    "AISGeneratorPort",
    "AIS_API_KEY_ENV",
    "AIS_API_KEY_FILE_ENV",
    "ALLOWED_MODELS",
    "DEEPINFRA_API_KEY_ENV",
    "DEEPINFRA_BASE_URL_ENV",
    "DEEPINFRA_MODEL",
    "DEEPSEEK_API_KEY_ENV",
    "DEEPSEEK_BASE_URL_ENV",
    "DEEPSEEK_MODEL",
    "DEEPSEEK_V4_FLASH_MODEL",
    "DEEPSEEK_V4_PRO_MODEL",
    "DEFAULT_DEEPINFRA_BASE_URL",
    "DEFAULT_DEEPSEEK_BASE_URL",
    "DEFAULT_GEMMA_AIS_BASE_URL",
    "DEFAULT_GEMMA_FALLBACK_BASE_URL",
    "DEFAULT_GEMMA_FALLBACK_MODEL",
    "DEFAULT_SUBSCRIPTION_EXECUTABLE",
    "DEFAULT_SUBSCRIPTION_MODEL",
    "FailoverGeneratorPort",
    "GEMMA_AIS_BASE_URL_ENV",
    "GEMMA_FALLBACK_API_KEY_ENV",
    "GEMMA_FALLBACK_API_KEY_FILE_ENV",
    "GEMMA_FALLBACK_BASE_URL_ENV",
    "GEMMA_FALLBACK_MODEL_ENV",
    "GEMMA_MODEL",
    "GEMMA_TIMEOUT_S",
    "GeneratorUnavailable",
    "HttpChatTransport",
    "LATENCY_WATCHDOG_MIN_SAMPLES",
    "LATENCY_WATCHDOG_MULTIPLIER",
    "LATENCY_WATCHDOG_WINDOW",
    "ProviderConcurrencyBudget",
    "RoundRobinGeneratorSelector",
    "SUBSCRIPTION_EXECUTABLE_ENV",
    "SUBSCRIPTION_HOST",
    "SUBSCRIPTION_MODEL_ENV",
    "SUBSCRIPTION_PROVIDER",
    "SubscriptionGeneratorPort",
    "TelemetryContext",
    "VERTEX_API_KEY_ENV",
    "VERTEX_API_KEY_FILE_ENV",
    "VERTEX_BASE_URL_ENV",
    "VertexGenerateContentTransport",
    "_build_generator_port",
    "_extract_text",
    "_extract_vertex_text",
    "_gemma_routes",
    "_gemini_ais_route",
    "_gemini_routes",
    "_get_bake_providers",
    "_require_exact_qualified_routes",
    "_require_qualification_route",
    "_validate_vertex_base_url",
    "_with_failover",
    "configure_provider_concurrency",
    "evaluate_latency_watchdog",
    "generator_model_id",
    "json_mode_enabled_for_model",
    "make_bake_generator",
    "make_generator",
    "make_logical_model_generator",
    "make_qualification_pinned_generator",
    "provider_call_slot",
    "qualification_route_credential_present",
    "telemetry_ctx",
    "validate_and_get_model",
    "validate_qualification_route_runtime",
]
